apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: routeoption-portal-cors
  namespace: gloo-system
spec:
  options:
    cors:
      allowCredentials: true
      allowHeaders:
      - '*'
      allowMethods:
      - GET
      - OPTIONS
      allowOrigin:
      - '*'
      # allowOriginRegex:
      # - .*