
##########################
#                        #
#        Example         #
#        Service         #
#                        #
#                        #
##########################
# quarkus service
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus
  name: quarkus
  namespace: quarkus
  annotations:
    harness.admin.mesh.cbp.dhs.gov/pipeline-number: "1.0.15"
spec:
  selector:
    matchLabels:
      app: quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
      - image: ddoyle/quarkus-rest-quickstart:1.0.15-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus
  namespace: quarkus
  labels:
    service: quarkus
  annotations:
    gloo.solo.io/scrape-openapi-source: /q/openapi
    gloo.solo.io/scrape-openapi-retry-delay: "5s"
    gloo.solo.io/scrape-openapi-pull-attempts: "10"
    gloo.solo.io/scrape-openapi-use-backoff: "true"
    harness.admin.mesh.cbp.dhs.gov/pipeline-number: "1.0.15"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: quarkus
